name: connectivity_manager_plus
description: >
  A Flutter utility package to monitor internet connectivity in real-time
  with customizable Snackbar, Alert Dialog, Full-Screen, or your own custom UI.
  Built on top of connectivity_plus. Open-source and developer-friendly.

# Remove this line to allow publishing on pub.dev
publish_to: 'https://pub.dev/packages/connectivity_manager_plus'

version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.5
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

# Extra metadata for pub.dev & GitHub
repository: https://github.com/BuckyBanaz/connectivity_manager_plus
homepage: https://github.com/BuckyBanaz/connectivity_manager_plus
issue_tracker: https://github.com/BuckyBanaz/connectivity_manager_plus/issues
documentation: https://pub.dev/documentation/connectivity_manager_plus/latest/
